tests:
  - changed-files:
    - any-glob-to-any-file: 'src/test/**/*'
    
java:
  - changed-files:
    - any-glob-to-any-file: '**/*.java'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    
markdown:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'pom.xml'


